### ISSUE TITLE
[Feature Request] Support for Foldable Callouts 

### ISSUE THREAD

**Issue by FelipeRearden** [Galacsh/obsidian-reading-view-enhancer#1]
Hello @Galacsh !!!!!

First of all, thank you very much for this amazing plugin !!! I have been looking for a plugin like this for a long time

This way, I am gonna generate some FR's for you based on my workflows.

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

---
### My FR

This first FR is simple to explain: would be amazing if yuo could add the `Collapse Indicator`  for **foldable Callouts**

```

> [!NOTE]- Title
> Contents

```

and 

```

> [!NOTE]+ Title
> Contents

```

---

Let me know if you need more information !!!

Have a great day 🌞

**Comment by Galacsh** [comment]
Hello @FelipeRearden !!!!!

First of all, thank you for the first feature request !!!

I'm glad to hear that this plugin is what you're looking for 😁

---

I didn't know that there is an foldable Callouts. Thanks for expanding my Obsidian knowledge :)

Looks like the feature is not that hard to implement. I'll try it soon!

**Comment by FelipeRearden** [comment]
> Hello @FelipeRearden !!!!!
> 
> First of all, thank you for the first feature request !!!
> 
> I'm glad to hear that this plugin is what you're looking for 😁

💙

> I didn't know that there is an foldable Callouts. Thanks for expanding my Obsidian knowledge :)
> 
> Looks like the feature is not that hard to implement. I'll try it soon!

Thats great news @Galacsh !!!! Thank you very much for bringing this new feature :)

Have a great day !!!!

**Comment by Galacsh** [comment]
oh,,, a sad news here. 😂

I found some bugs on current code. I'll work on this feature after known bugs fixed.

**Comment by FelipeRearden** [comment]
> oh,,, a sad news here. 😂
> 
> I found some bugs on current code. I'll work on this feature after known bugs fixed.

Thanks for the feedback @Galacsh !!!!!

Its okay !!!! I hope you easy find solutions for the new bugs ☀️ 

Good luck and lets keep talking :)

Have a great day 🙏

**Comment by Galacsh** [comment]
Newly released version now handles folding/unfolding collapsible callouts!

Thank you for your suggestion!
