### ISSUE TITLE
[Feature Request] Command to select a block 

### ISSUE THREAD

**Issue by Galacsh** [Galacsh/obsidian-reading-view-enhancer#5]
> From 0.1.1, since the style is manually injected in the `<head>...</head>`, the plugin doesn't need `styles.css`.
> 
> I've uploaded this video on the `README.md`. Check this out if this fits your needs.

@Galacsh thank you for the reply !

Let me ask you 2 questions to see if I understood correctly ...

1️⃣ From version 0.1.1 I have to execute a `click` operation before using the keyboard shortcuts ?

2️⃣ There is no support for Obsidian Mobile?

---

I am asking you this because my idea is to use your plugin 100% full keyboard hotkeys: open a note on Reading mode (make it the active note) and then hitting keyboard hotkeys to navigate between headers and callouts. 

Moreover I use Obsidian Mobile on a iPad with a mouse and keyboard. If possible, I would like to have the same workflow on iPad that I have on Desktop 🙏

Thanks for reading this, my idea is to share with you my workflow to see if fits on your plugin idea 

Let me know what you think !

Have a great day ☀️

_Originally posted by @FelipeRearden in https://github.com/Galacsh/obsidian-reading-view-enhancer/issues/2#issuecomment-1490214879_

**Comment by Galacsh** [comment]
Resolved by merging #4

Released in version [0.1.2](https://github.com/Galacsh/obsidian-reading-view-enhancer/releases/tag/0.1.2)

**Comment by Galacsh** [comment]
Hello @FelipeRearden !

Oh.. Since I just tested on the emulated mobile env, I didn't know that it actually doesn't work on Mobile.
So sorry for that and So thank you for testing!

I'll try to fix it and let you know when it's fixed!

Again, thanks for your help! your issue is very helpful 😁

**Comment by FelipeRearden** [comment]
> I've released the version [0.1.3](https://github.com/Galacsh/obsidian-reading-view-enhancer/releases/tag/0.1.3)(now, the latest) for fixing this problem. I've tested 0.1.3 with my iPhone + Bluetooth keyboard and it works well for me.

Working absolutely perfect on Obsidian Mobile with iPadOS 16.2 on version 0.1.3 🚀🚀🚀

---

Thank you very much for your effort to make this work, I am gonna start playing on my main vault after the merge and I let you now if I find something . I am so happy !!!!!!!

--- 

### Question about CSS

Let me ask one more thing, now about CSS. 

Would you mind sharing with me what is the css code that I have use to target the `block selector` style  ? I want to test in my vault with `border` and/or `box-shadow` instead of `background-color `. 

I don't know yet how I want to style, but I wanna test a few styles :)

Thank you very much @Galacsh !!! You are super 🥇

**Comment by Galacsh** [comment]
> Working absolutely perfect on Obsidian Mobile with iPadOS 16.2 on version 0.1.3 🚀🚀🚀

Glad to hear that it works !! @FelipeRearden 

### Answer

This is the css that sets the style of selected block.

```css
.rve-selected-block {
  position: relative;
}

.rve-selected-block::before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  pointer-events: none;
  background-color: {{BLOCK_COLOR}}1a;
}
```

You can find this code here.

https://github.com/Galacsh/obsidian-reading-view-enhancer/blob/be4ade8e519c97ea71c1c61c7c7a4fd9f22ed627/src/styles.ts#L38-L51

And also in the released `main.js` line 78 ~ 91.

---

To override this css, you could do something like this using [Specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity).

```css
.markdown-preview-view .rve-selected-block::before {
  background-color: #0c7ef085;
}
```

**Comment by FelipeRearden** [comment]
That's perfect !!!!! 

Thank you very much @Galacsh !!!

I wish you a fantastic day ☀️
