### ISSUE TITLE
FR: Customizable keys / use vim bindings

### ISSUE THREAD

**Issue by chrisgrieser** [Galacsh/obsidian-reading-view-enhancer#9]
great plugin, will be using this regularly.

Could the keys be customizable, for example to use `hjkl` instead of the arrow keys for us vim users? 🙏

**Comment by Galacsh** [comment]
Thank you for your awesome idea!

I've added a feature that allows simple customization of key bindings.
After updating the plugin to ^0.1.5, you can use this feature.

One day I'll try to make this plugin support key sequences, e.g. `gg` / `G` / `3j`.  
(But not right now.)

Again, thanks for the idea. :)
